/*
drop table members;
insert into members values (null, 'e', 'e', 'e', 'e', null, null, null, null, now(), 0);
select * from members;

DROP TABLE MEMBERS_INFO;
INSERT INTO MEMBERS_INFO VALUES (0, '일반회원');
INSERT INTO MEMBERS_INFO VALUES (1, '소셜회원');
INSERT INTO MEMBERS_INFO VALUES (99, '관리자');
SELECT * FROM MEMBERS_INFO;
*/

CREATE TABLE MEMBERS_INFO (
	M_TYPE TINYINT PRIMARY KEY,
    M_TYPE_NAME VARCHAR(10) NOT NULL
);
SELECT * FROM MEMBERS_INFO;

CREATE TABLE MEMBERS (
	M_AUTOINCREMENT INT AUTO_INCREMENT PRIMARY KEY,
	M_ID VARCHAR(20) NOT NULL UNIQUE,
    M_PW VARCHAR(20) NOT NULL,
    M_NAME VARCHAR(20) NOT NULL,
    M_NICK VARCHAR(20) NOT NULL UNIQUE,
    M_BIRTH DATE,
    M_EMAIL VARCHAR(100),
    M_TEL VARCHAR(100),
    M_ADDRESS VARCHAR(100),
    M_REGDATE DATETIME,
    M_TYPE TINYINT NOT NULL,
	CONSTRAINT FK_MEMBERS_TYPE 
		FOREIGN KEY (M_TYPE) REFERENCES MEMBERS_INFO (M_TYPE)
			ON UPDATE CASCADE
            ON DELETE CASCADE
);
SELECT * FROM MEMBERS;